name: Continuous Playit Server (SSH and Apache)

on:
 workflow_dispatch:

jobs:
 server_node:
 runs-on: ubuntu-latest

 env:
  API_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  PLAYIT_CONFIG_DIR: /home/none/.playit

 steps:
 - name: Checkout code
  uses: actions/checkout@v4

 - name: Restore Persisted Server Data (Apache + Playit)
  uses: actions/download-artifact@v4
  with:
  name: persisted-server-data
  path: .

 - name: Setup Environment and Start Services
  run: |
  sudo apt-get update

  # --- A. Настройка пользователя и SSH ---
  sudo apt-get install -y openssh-server

  NEW_USER="none"
  PASSWORD="h4ck3d" 

  if ! id -u $NEW_USER >/dev/null 2>&1; then
   sudo useradd -m -s /bin/bash $NEW_USER
   echo "$NEW_USER:$PASSWORD" | sudo chpasswd
   sudo usermod -aG sudo $NEW_USER
  fi

  sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  sudo sed -i 's/^PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
  sudo service ssh restart

  # --- B. Настройка Apache ---
  sudo apt-get install -y apache2

  # Восстановление конфигов Apache
  if [ -d "etc/apache2" ]; then
   sudo rsync -a etc/apache2/ /etc/apache2/
  fi

  sudo service apache2 start

  # --- C. Playit.gg CLI ---
  curl -SsL https://playit-cloud.githubusercontent.com/playit-cli/install/linux/playit-cli -o playit
  chmod +x playit

  # Создание директории для конфига Playit
  mkdir -p ${{ env.PLAYIT_CONFIG_DIR }}

  # Восстановление конфигов Playit (если существуют)
  if [ -d "playit" ]; then
   rsync -a playit/ ${{ env.PLAYIT_CONFIG_DIR }}/
   echo "Restored Playit config."
  fi

  # Установка переменной HOME для Playit CLI
  export HOME=/home/none

  # Запуск Playit
  echo "Starting Playit CLI..."
  # Проверка наличия ключа в конфиге. Если нет, запускаем с --connect.
  if [ ! -f "${{ env.PLAYIT_CONFIG_DIR }}/playit.toml" ] || ! grep -q "secret_key" "${{ env.PLAYIT_CONFIG_DIR }}/playit.toml"; then
   echo "--- ПЕРВЫЙ ЗАПУСК ИЛИ АВТОРИЗАЦИЯ. Ищите ссылку в логах ниже. ---"
   ./playit --port 22 --protocol tcp --address 127.0.0.1 --connect &
   sleep 5
   # Даем 3 минуты на авторизацию.
   sleep 180 
  else
   echo "Используется сохраненный ключ Playit.gg."
   ./playit --port 22 --protocol tcp --address 127.0.0.1 &
   sleep 10
  fi

 - name: Save Persisted Server Data (Apache + Playit)
  uses: actions/upload-artifact@v4
  with:
  name: persisted-server-data
  path: |
   /etc/apache2/
   /home/none/.playit/
  retention-days: 7 

 - name: Self-Restart and Wait
  run: |
  REPO_NAME="${{ github.repository }}"
  WORKFLOW_ID="playit-server.yml"

  curl -X POST \
  -H "Accept: application/vnd.github.com/v3+json" \
  -H "Authorization: token ${{ env.API_TOKEN }}" \
  "https://api.github.com/repos/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches" \
  -d '{"ref":"${{ github.ref }}"}'

  SLEEP_TIME=20999 
  sleep $SLEEP_TIME
